/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package measurementCC;

import org.junit.jupiter.api.Test;

import measurementcontract.MeasurementAsset;

import static org.junit.jupiter.api.Assertions.*;

import java.time.Instant;



class MeasurementAssetTests {

    private String sensorid = "sensor1";
    private String org = "Organisation 1";
    private int data = 2000;
    private String timestamp = Instant.now().toString();

    MeasurementAsset asset = new MeasurementAsset(sensorid, org, data, timestamp);


    @Test void isequalMeasurementAsset() {
        assertEquals(asset, asset);
    }

    @Test void isequalsecond(){
        MeasurementAsset asset2 = new MeasurementAsset(sensorid, org, data, timestamp);
        assertEquals(asset, asset2);
    }

    @Test void checkJsontoString(){
        String jsonString = "{\"sensorid\":\"sensor1\",\"organisation\":\"Organisation 1\",\"data\":2000,\"timestamp\":\""+ timestamp + "\"}";
        assertEquals(asset.toJSON(), jsonString);
    }

    @Test void checkJsontoObject(){
        String jsonString = "{\"sensorid\":\"sensor1\",\"organisation\":\"Organisation 1\",\"data\":2000,\"timestamp\":\""+ timestamp + "\"}";
        MeasurementAsset asset2 = MeasurementAsset.fromJSON(jsonString);
        assertEquals(asset, asset2);
    }

    @Test void isequalJSON(){
        String json = asset.toJSON();
        MeasurementAsset asset2 = MeasurementAsset.fromJSON(json);
        assertEquals(asset, asset2);
    }

    @Test void isNotEqualTo(){
        MeasurementAsset asset2 = new MeasurementAsset("sensor 1", org, data, timestamp);
        assertFalse(asset.equals(asset2));
    }

}
